### PR TITLE
Update docs_stable.yml

### PR DESCRIPTION
**Pull request by yunchu**
### Summary
Fixing typo in testenv name on tox.ini for building docs.

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by vinnamkim — COMMENTED** [review]
Should this be merged to `develop`, not `releases/1.2.0`?

**Comment by yunchu** [comment]
> Should this be merged to `develop`, not `releases/1.2.0`?

For testing, it needs to be merged `develop` first.

**Comment by vinnamkim** [comment]
> > Should this be merged to `develop`, not `releases/1.2.0`?
> 
> For testing, it needs to be merged `develop` first.

Couldn't it be triggered by the workflow_dispatch event just for testing? 

image

**Comment by yunchu** [comment]
@vinnamkim oops, you are right. close it for a while.

**Pull request closed without merging**
