### PR TITLE
Mergeback 1.5.1 to develop

### PR DESCRIPTION
**Pull request by yunchu**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added the description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md).​
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by vinnamkim — COMMENTED** [review]
Why does the merge commit at the end https://github.com/openvinotoolkit/datumaro/pull/1197/commits/8b16146c893a64965408fdf9599771a39cad2e1a have so many changes in it? Almost of them seem already included in the previous commits.

**Comment by yunchu** [comment]
@vinnamkim I don't know exact reason. this is what I can see on the my local.
image

**Comment by vinnamkim** [comment]
This merge-back process gives me https://github.com/openvinotoolkit/datumaro/pull/1198/commits/aa3c927068781e74b222719ef53b7e645c20abb8

```console
(datumaro) vinnamki@vinnamki:~/datumaro$ git checkout releases/1.5.0 
(datumaro) vinnamki@vinnamki:~/datumaro$ git checkout -B merge-back/releases/1.5.0
(datumaro) vinnamki@vinnamki:~/datumaro$ git merge develop

Resolve merge conflicts...

(datumaro) vinnamki@vinnamki:~/datumaro$ git show HEAD
commit aa3c927068781e74b222719ef53b7e645c20abb8 (HEAD -> merge-back/releases/1.5.0, origin/merge-back/releases/1.5.0)
Merge: 375d18418 be2cab9c6
Author: Kim, Vinnam <vinnam.kim@intel.com>
Date:   Tue Nov 21 17:14:38 2023 +0900

    Merge branch 'develop' into merge-back/releases/1.5.0
    
    Signed-off-by: Kim, Vinnam <vinnam.kim@intel.com>

diff --cc CHANGELOG.md
index e34dd8850,774733b64..8e73eb5e3
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@@ -28,9 -32,16 +38,18 @@@ and this project adheres to [Semantic V
    (<https://github.com/openvinotoolkit/datumaro/pull/1159>, <https://github.com/openvinotoolkit/datumaro/pull/1161>)
  - Fix memory unbounded Arrow data format export/import
    (<https://github.com/openvinotoolkit/datumaro/pull/1169>)
 +- Update CVAT format doc to bypass warning
 +  (<https://github.com/openvinotoolkit/datumaro/pull/1183>)
  
+ ## 15/09/2023 - Release 1.5.0
```

**Comment by yunchu** [comment]
is it possible to show different results when run the merge command on the develop to releases/1.5.0? in case of mind, did it.

**Comment by vinnamkim** [comment]
I just did in the reversed direction. Yea, it gives us not interpretable well one https://github.com/openvinotoolkit/datumaro/pull/1199/commits/68bcb41599825d12bf51a385046c54dce243aa0c in the GitHub UI. I think it would be good not to create the merge commit in this way next time.

```console
(datumaro) vinnamki@vinnamki:~/datumaro$ git checkout develop
(datumaro) vinnamki@vinnamki:~/datumaro$ git checkout -B merge-back-rev/releases/1.5.0
(datumaro) vinnamki@vinnamki:~/datumaro$ git merge releases/1.5.0 

Resolve merge conflicts...

(datumaro) vinnamki@vinnamki:~/datumaro$ git show HEAD
commit 68bcb41599825d12bf51a385046c54dce243aa0c (HEAD -> merge-back-rev/releases/1.5.0)
Merge: be2cab9c6 375d18418
Author: Kim, Vinnam <vinnam.kim@intel.com>
Date:   Tue Nov 21 17:25:02 2023 +0900

    Merge remote-tracking branch 'upstream/releases/1.5.0' into merge-back-rev/releases/1.5.0
    
    Signed-off-by: Kim, Vinnam <vinnam.kim@intel.com>

diff --cc CHANGELOG.md
index 774733b64,e34dd8850..8e73eb5e3
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@@ -32,16 -28,9 +38,18 @@@ and this project adheres to [Semantic V
    (<https://github.com/openvinotoolkit/datumaro/pull/1159>, <https://github.com/openvinotoolkit/datumaro/pull/1161>)
  - Fix memory unbounded Arrow data format export/import
    (<https://github.com/openvinotoolkit/datumaro/pull/1169>)
+ - Update CVAT format doc to bypass warning
+   (<https://github.com/openvinotoolkit/datumaro/pull/1183>)
  
 +## 15/09/2023 - Release 1.5.0
```

**Review by vinnamkim — APPROVED** [review]
LGTM.

**Comment by yunchu** [comment]
for improving readability, i will open new PR for this mergeback.

**Pull request closed without merging**
