### PR TITLE
Support subset for KITTI 3D format

### PR DESCRIPTION
**Pull request by sooahleex**
### Summary

- Support subset structure for KITTI 3d format
- Update media type from PointCloud to Image

### How to test

- Add unit test

### Checklist

- [X] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [X] I have added the description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md).​
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by kprokofi** [comment]
I have a quick question. Will it support "train", "val" and "test" folders right? What kind of structure is expected as input?

**Comment by sooahleex** [comment]
> I have a quick question. Will it support "train", "val" and "test" folders right? What kind of structure is expected as input?
@kprokofi I added the test asset for subset like below [kitti_3d_with_subset](https://github.com/sooahleex/datumaro/tree/fix/support_subset_kitti3d/tests/assets/kitti_dataset/kitti_3d_with_subset)

**Comment by kprokofi** [comment]
> > I have a quick question. Will it support "train", "val" and "test" folders right? What kind of structure is expected as input?
> > @kprokofi I added the test asset for subset like below [kitti_3d_with_subset](https://github.com/sooahleex/datumaro/tree/fix/support_subset_kitti3d/tests/assets/kitti_dataset/kitti_3d_with_subset)

Ok, I see. Thank you! I will prepare the same structure then.

**Comment by kprokofi** [comment]
@wonjuleee , could you review?

**Review by wonjuleee — APPROVED** [review]

**Comment by sovrasov** [comment]
Hi @wonjuleee @sooahleex is there any reason not to support mmdet's kitty layout?
https://mmdetection3d.readthedocs.io/en/v0.17.1/datasets/kitti_det.html
```
mmdetection3d
├── mmdet3d
├── tools
├── configs
├── data
│   ├── kitti
│   │   ├── ImageSets
│   │   ├── testing
│   │   │   ├── calib
│   │   │   ├── image_2
│   │   │   ├── velodyne
│   │   ├── training
│   │   │   ├── calib
│   │   │   ├── image_2
│   │   │   ├── label_2
│   │   │   ├── velodyne
```
I think many people'd prefer to use mmdet's data preparation script

**Comment by sooahleex** [comment]
> Hi @wonjuleee @sooahleex is there any reason not to support mmdet's kitty layout? https://mmdetection3d.readthedocs.io/en/v0.17.1/datasets/kitti_det.html
> 
> ```
> mmdetection3d
> ├── mmdet3d
> ├── tools
> ├── configs
> ├── data
> │   ├── kitti
> │   │   ├── ImageSets
> │   │   ├── testing
> │   │   │   ├── calib
> │   │   │   ├── image_2
> │   │   │   ├── velodyne
> │   │   ├── training
> │   │   │   ├── calib
> │   │   │   ├── image_2
> │   │   │   ├── label_2
> │   │   │   ├── velodyne
> ```
> 
> I think many people'd prefer to use mmdet's data preparation script

@sovrasov I only considered the structure of the kitti dataset like [kitti-3d-object-detection-dataset](https://www.kaggle.com/datasets/garymk/kitti-3d-object-detection-dataset/data), and the use case for our product is limited to monocular 3D object detection. So I did not support point clouds from the lidar sensor or any additional information, but I fully agree with our opinion that the public prefers to use the kitti layout of mmdetection. I will consider supporting this structure in the next release.

**Pull request merged**
