### PR TITLE
Factor out annotation-related functionality into a separate module

### PR DESCRIPTION
**Pull request by IRDonch**
### Summary
Annotations are only tangentially related to extractors, so I don't think they belong in `extractor.py`. `extractor.py` is also a large module, so removing a chunk of it makes it easier to navigate.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [x] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by IRDonch** [comment]
@zhiltsov-max This PR is incomplete (I haven't updated the examples in the documentation yet). Let me know if you agree with this refactoring and if you do, I'll finish it.

**Comment by zhiltsov-max** [comment]
Thought of it. It does not really matter until we have stable and documented API, but this breaks the library API.

**Comment by IRDonch** [comment]
> It does not really matter until we have stable and documented API, but this breaks the library API.

I could add compatibility exports if that's your concern. Although I kinda figured that with the versioning changes we're pretty much breaking all compatibility anyway. :P

**Comment by IRDonch** [comment]
So what should I do? Should I add the compatibility exports?

**Comment by zhiltsov-max** [comment]
Let's put off the PR till we introduce the stable API after the versioning release.

**Comment by IRDonch** [comment]
> Let's put off the PR till we introduce the stable API after the versioning release.

I don't think that's a good course of action; it would be much harder to bring the PR up-to-date at that point (which could be long into the future) than it would be to just add compatibility exports now and then remove them later. Plus, by merging this now we can improve the navigability of `extractor.py` in the interim (I initiated this refactoring in the first place because I kept getting lost in it).

**Comment by zhiltsov-max** [comment]
Ok, then add compatibility exports and it is ready.

**Comment by IRDonch** [comment]
OK, done and updated the documentation.

**Review by zhiltsov-max — APPROVED** [review]

**Pull request merged**
