### PR TITLE
Add notebook for importing/exporting segmentation data

### PR DESCRIPTION
**Pull request by wonjuleee**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added the description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md).​
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by cih9088 — CHANGES_REQUESTED** [review]
The dataset directory structure for `cityscapes` should follow [this one](https://openvinotoolkit.github.io/datumaro/latest/docs/explanation/formats/cityscapes.html#import-cityscapes-dataset).

It would be better to revert changes regarding `cityscapes` dataset and put [the `cityscapes` format documentation link](https://openvinotoolkit.github.io/datumaro/latest/docs/explanation/formats/cityscapes.html#import-cityscapes-dataset) into the notebook and tell users that you should unarchive the zip files in this way to import them into Datumaro.

**Comment by wonjuleee** [comment]
> The dataset directory structure for `cityscapes` should follow [this one](https://openvinotoolkit.github.io/datumaro/latest/docs/explanation/formats/cityscapes.html#import-cityscapes-dataset).
> 
> It would be better to revert changes regarding `cityscapes` dataset and put [the `cityscapes` format documentation link](https://openvinotoolkit.github.io/datumaro/latest/docs/explanation/formats/cityscapes.html#import-cityscapes-dataset) into the notebook and tell users that you should unarchive the zip files in this way to import them into Datumaro.

I updated the Cityscapes document instead. Thank you for letting me know this.

**Comment by cih9088** [comment]
> I updated the Cityscapes document instead. Thank you for letting me know this.

Since we have agreed to change the `cityscapes` format directory structure, we should let users know it as it might break their workflow when they update Datumaro.
Could you add it to the `CHANGELOG.md`?

**Comment by wonjuleee** [comment]
> > I updated the Cityscapes document instead. Thank you for letting me know this.
> 
> Since we have agreed to change the `cityscapes` format directory structure, we should let users know it as it might break their workflow when they update Datumaro. Could you add it to the `CHANGELOG.md`?

I updated.

**Review by cih9088 — APPROVED** [review]

**Review by sooahleex — APPROVED** [review]

**Pull request merged**
