### PR TITLE
Fix not saving extra images of PointCloud in datumaro format

### PR DESCRIPTION
**Pull request by cih9088**
### Summary
The extra images were not saved during Datumaro format export.

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [x] I have added the description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md).​
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by vinnamkim — COMMENTED** [review]
Can we have a test for it?

**Comment by vinnamkim** [comment]
> Can we have a test for it?

We could use this asset, https://github.com/openvinotoolkit/datumaro/tree/develop/tests/assets/sly_pointcloud_dataset

**Comment by cih9088** [comment]
> Can we have a test for it?

If only [this part](https://github.com/openvinotoolkit/datumaro/blob/develop/tests/utils/test_utils.py#L251-L267) is replaced with `test.assertEqual(item_a.media, item_b.media)` to compare contents.

As you commented in the code block, just replacing it causes lots of error. The `Image` refactoring branch I'm working on fixed it and hopefully it got merged soon.

**Review by vinnamkim — DISMISSED** [review]
LGTM.

**Review by sooahleex — DISMISSED** [review]
Looks good to me.

**Review by wonjuleee — APPROVED** [review]

**Review by vinnamkim — APPROVED** [review]
LGTM.

**Comment by cih9088** [comment]
> > Can we have a test for it?
> 
> If only [this part](https://github.com/openvinotoolkit/datumaro/blob/develop/tests/utils/test_utils.py?rgh-link-date=2023-04-06T06%3A05%3A25Z#L251-L267) is replaced with `test.assertEqual(item_a.media, item_b.media)` to compare contents.
> 
> As you commented in the code block, just replacing it causes lots of error. The `Image` refactoring branch I'm working on fixed it and hopefully it got merged soon.

Fixed in https://github.com/openvinotoolkit/datumaro/pull/921

**Pull request merged**
