### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by IRDonch**
### Summary
Fix various misspellings/typos that I found with codespell.

### How to test
N/A

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by zhiltsov-max — APPROVED** [review]
Is it possible to do automatically on CI?

**Comment by IRDonch** [comment]
> Is it possible to do automatically on CI?

I don't think you can do it in a reliable way, because whether a word is actually a misspelling or not can be heavily context-dependent. For example, codespell suggests to replace "ans" with "and" (which I did in this PR), but in another context "ans" could be an abbreviation for "answer" and thus not an error. So I don't think you can use codespell without human review of the results.

**Comment by IRDonch** [comment]
Well, in all fairness... if you're willing to tolerate some false negatives, you could keep an ignore list in the repository, and just add all ambiguous words there. I suppose that would be better than nothing, although it means that contributors have to not blindly trust the spellchecker and add words to the ignore list sometimes. :-)

**Comment by zhiltsov-max** [comment]
I think, we can leave it in a list of recommended extensions for the environment setup in the developer guide.

**Pull request merged**
