### PR TITLE
coco_format: add an option to preserve original category IDs when extracting

### PR DESCRIPTION
**Pull request by IRDonch**
### Summary
This is needed for potential integration into Accuracy Checker, since AC has this option as well.

As a side effect, refactor the loading of categories to remove duplication between the panoptic segmentation and other task types.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [x] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by zhiltsov-max — COMMENTED** [review]
I suggest to use more short "keep" instead of "preserve".

Update the format documentation.

**Comment by IRDonch** [comment]
> I suggest to use more short "keep" instead of "preserve".

Okay, done.

> Update the format documentation.

I would, but there's no documentation for the importer/extractor API in the first place.

**Comment by zhiltsov-max** [comment]
> I would, but there's no documentation for the importer/extractor API in the first place.

How it hinders to describing import parameters in the format documentation? There is nothing about API at all.

**Comment by IRDonch** [comment]
The parameter currently only exists on the API level. Should I add a corresponding CLI option?

**Comment by zhiltsov-max** [comment]
IMO, there's a little sense, if it is an API-only parameter. Maybe, I'd invest in auto-generation of cli parsers from the ctor parameters, but not now.

**Comment by IRDonch** [comment]
OK, I added a CLI option equivalent and documented it.

**Review by zhiltsov-max — APPROVED** [review]

**Pull request merged**
