### PR TITLE
Fix imagenet importer

### LINKED ISSUE #336: Import ImageNet dataset
### Steps to reproduce problem
1. Download and extract ImageNet dataset for image classification: [link](https://www.kaggle.com/c/imagenet-object-localization-challenge/data);
2. Add the loaded dataset into a Datumaro project;
3. Run `datum info`.

### Current behaviour
ImageNet dataset has ~1.2m images, but in the `info` output we can see that imported dataset has only 69647, and also these images have wrong labels.

### Expected behaviour
Correct import.

### Environment
`git log -1`: 7e35c8

### PR DESCRIPTION
**Pull request by kirill-sizov**
### Summary
Resolved #336 by changing id for items.

### How to test
Import the original ImageNet dataset with Datumaro.

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [x] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by zhiltsov-max — COMMENTED** [review]
Could you please check is the original dataset contains the same images in different directories? You can use `operations.find_unique_images()`.

Maybe, we should append the label directory in front of the item id as well as in other formats?

**Comment by kirill-sizov** [comment]
> Could you please check is the original dataset contains the same images in different directories? You can use `operations.find_unique_images()`.
> 
> Maybe, we should append the label directory in front of the item id as well as in other formats?

@zhiltsov-max I checked, the original dataset has the same images in different directories but all of them have different names.

**Review by zhiltsov-max — DISMISSED** [review]

**Comment by zhiltsov-max** [comment]
Please fix the remaining test

**Review by zhiltsov-max — COMMENTED** [review]
Update the changelog

**Pull request merged**
