### PR TITLE
Remove hacks that were added to work around issues in pycocotools

### PR DESCRIPTION
**Pull request by IRDonch**
### Summary

Ignore this for now. I'm just making sure that the changes I made in ppwwyyxx/cocoapi#6 do actually resolve the issues for which the workarounds were added.

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by IRDonch** [comment]
Okay, looks good. I'll close it for now and revive it if/when my patch to pycocotools gets accepted and a new release is published.

**Comment by IRDonch** [comment]
> I'll close it for now and revive it if/when my patch to pycocotools gets accepted and a new release is published.

This has now happened! As such, I'm reopening this.

**Review by zhiltsov-max — APPROVED** [review]
It's great news! I feel, many projects have == 2.0.2 in requirements, though. Let's merge after the gitpython problem in the tests is resolved.

**Comment by IRDonch** [comment]
Looks like someone has already submitted a fix for GitPython: gitpython-developers/GitPython#1394.

**Review by zhiltsov-max — APPROVED** [review]

**Pull request merged**
