### PR TITLE
Skip nbqa-ruff installation with python3.7

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary
- Skip `nbqa-ruff` installation with python3.7. `nbqa[toolchain]==1.6.3` is not supported for python 3.7 but `nbqa-ruff` is supported with `nbqa>1.5.3`)
- Related PR: #892 

image

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added the description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md).​
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by vinnamkim — COMMENTED** [review]
Please update this too.

https://github.com/openvinotoolkit/datumaro/blob/d273506aa73fbcb7a495a9a3dcbdba3a626375b1/.pre-commit-config.yaml#L60

**Comment by JihwanEom** [comment]
> Please update this too.
> 
> https://github.com/openvinotoolkit/datumaro/blob/d273506aa73fbcb7a495a9a3dcbdba3a626375b1/.pre-commit-config.yaml#L60

Reflected, thank you!

**Comment by JihwanEom** [comment]
@vinnamkim, `nbqa-ruff` is not supported in `nbqa==1.5.3`, so I have updated the pre-commit configuration to skip the installation of `nbqa-ruff` when using Python 3.7 and to install it only for Python 3.8 and higher versions. Can you please review again the changes?

**Comment by vinnamkim** [comment]
> @vinnamkim, `nbqa-ruff` is not supported in `nbqa==1.5.3`, so I have updated the pre-commit configuration to skip the installation of `nbqa-ruff` when using Python 3.7 and to install it only for Python 3.8 and higher versions. Can you please review again the changes?

In this case, you may introduce if-else statement to `tests/requirement.txt` to install `nbqa==1.5.3` for Python3.7 and `nbqa==1.6.3` for other versions. https://github.com/openvinotoolkit/datumaro/pull/894/commits/c3c8963ad65085fa8fda96a5a11d083ca0f44364 cannot pass CI as same as before.

**Review by vinnamkim — APPROVED** [review]
LGTM.

**Review by sooahleex — APPROVED** [review]

**Review by cih9088 — APPROVED** [review]

**Pull request merged**
