### PR TITLE
Add whitespace error checking to GitHub Actions

### PR DESCRIPTION
**Pull request by IRDonch**
### Summary
Add a job that checks the project for whitespace errors (using `git diff --check`). The contribution guide already suggests no trailing whitespace; this helps enforce it.

The new job is called `lint` - my intention that in the future, further lint-like steps could be added to it.

Fix all existing errors in the codebase.

### How to test
N/A

### Checklist

- [x] I submit my changes into the `develop` branch
- ~~[ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)~~ N/A - no user-visible changes
- ~~[ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
I'd want to move towards having some kind of automatic code formatting. Probably, this PR could be considered a first step.

**Review by zhiltsov-max — APPROVED** [review]
The only this is that I'm not sure we want it for all files. Because some formats can rely on this.

**Comment by IRDonch** [comment]
> The only this is that I'm not sure we want it for all files. Because some formats can rely on this.

It's possible to customize which checks are done for specific files (or file types) by adding Git attributes, so we can always add an exception if needed.

**Comment by zhiltsov-max** [comment]
Let's exclude `tests/assets/`.

**Comment by IRDonch** [comment]
> Let's exclude `tests/assets/`.

Why? None of the current files require trailing spaces.

**Comment by zhiltsov-max** [comment]
Because such restriction has no foundation for these files.

**Pull request merged**
