### PR TITLE
Clean up .pylintrc

### PR DESCRIPTION
**Pull request by IRDonch**
### Summary

* Remove obsolete options and checkers.
* Remove the commented-out value of `disable`.
* Use the new code for a checker whose code changed.

### How to test

N/A

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
Does it require full rescanning?

**Comment by IRDonch** [comment]
> Does it require full rescanning?

What do you mean?

**Comment by zhiltsov-max** [comment]
If CI scans only changed files, it is needed.

**Comment by IRDonch** [comment]
CI scans all files.

**Review by zhiltsov-max — APPROVED** [review]

**Pull request merged**
