### PR TITLE
Add new docs with Sphinx (.rst)

### PR DESCRIPTION
**Pull request by chuneuny-emily**
### **This PR contains**
**User Documentation Conversion**
 - Reconstruing categories
 - Replacing build tool: Hugo -> Sphinx
 - Replacing md files to rst files
 - Aligning themes & template to OTX

**Developer Documentation Conversion**
 - Reconstruing categories
 - Aligning themes & template to OTX

**One Unified Datumaro Documentation**
 - Combining user documentation and developer documentation 

### How to test
$ cd datumaro/docs
$ make html
 

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by vinnamkim — CHANGES_REQUESTED** [review]
I briefly saw the changes of this draft and I know this is just a draft. However, why do we have to change all markdown files to `*.rst`? Although we move to Sphinx, we can use them as well: https://www.sphinx-doc.org/en/master/usage/markdown.html.

**Comment by chuneuny-emily** [comment]
> I briefly saw the changes of this draft and I know this is just a draft. However, why do we have to change all markdown files to `*.rst`? Although we move to Sphinx, we can use them as well: https://www.sphinx-doc.org/en/master/usage/markdown.html.

I got a feedback by doc team that Sphinx uses the RST markup language by default, and Intel recommend to use RST, not markdown.

**Comment by vinnamkim** [comment]
> > I briefly saw the changes of this draft and I know this is just a draft. However, why do we have to change all markdown files to `*.rst`? Although we move to Sphinx, we can use them as well: https://www.sphinx-doc.org/en/master/usage/markdown.html.
> 
> I got a feedback by doc team that Sphinx uses the RST markup language by default, and Intel recommend to use RST, not markdown.

I read what you sent me but in the last page I can see "shift to rst for the main portion of documents, **use markdown as a secondary.**". I believe this direction does not mean that we have to move to `rst` right now and never use `md` anymore.

I have no objection to moving to `rst`, but it cannot be allowed in this way. You made **228 file changes and 13,438 lines changes in this single PR.** This is the number that can never be reviewed.

I found three documentation updates in the latest develop that you already missed in this PR:
1. YoloLooseFormat
https://github.com/openvinotoolkit/datumaro/blob/070d716e746c9ff44b9bc5d2d8b947736954696d/site/content/en/docs/formats/yolo.md?plain=1#L114-L162
2. YoloUltralyticsFormat
https://github.com/openvinotoolkit/datumaro/blob/develop/site/content/en/docs/formats/yolo_ultralytics.md
3. Searcher
https://github.com/openvinotoolkit/datumaro/blob/develop/site/content/en/docs/user-manual/command-reference/searcher.md

My opinion is that **you should gradually migrate from `md` to `rst`** and the amount of PR you put up at once should be reasonable for reviews.

**Comment by chuneuny-emily** [comment]
> My opinion is that **you should gradually migrate from `md` to `rst`** and the amount of PR you put up at once should be reasonable for reviews.

Additional work has not yet been done on the documents added after the time the doc was first created, and work on the detailed pages has not yet been completed. I made this PR first so that Yunchu could start the build doc work in CI at the same time.

While working on it, I realized belatedly that the amount of work was enormous. Are you want to turn files except index back into .md files again? @wonjuleee  What do you think of it?

**Comment by wonjuleee** [comment]
> > My opinion is that **you should gradually migrate from `md` to `rst`** and the amount of PR you put up at once should be reasonable for reviews.
> 
> Additional work has not yet been done on the documents added after the time the doc was first created, and work on the detailed pages has not yet been completed. I made this PR first so that Yunchu could start the build doc work in CI at the same time.
> 
> While working on it, I realized belatedly that the amount of work was enormous. Are you want to turn files except index back into .md files again? @wonjuleee What do you think of it?

In my opinion, it looks better to let doc files staying with `.md` for now.

**Pull request closed without merging**
